plugins {
	id 'java'
	id 'org.springframework.boot' version '2.7.18'
	id 'io.spring.dependency-management' version '1.1.7'
}

group = 'com.github.desktop'
version = '0.0.1-SNAPSHOT'

java {
	toolchain {
		languageVersion = JavaLanguageVersion.of(11)
	}
}

repositories {
	mavenCentral()
	maven {
		name = "GitHubPackages"
		url = uri("https://maven.pkg.github.com/Asli-RI/spring-commons")
		credentials {
			username = project.findProperty("user")
			password = project.findProperty("token")
		}
	}
}

dependencies {
	// Data JPA
	implementation("org.springframework.boot:spring-boot-starter-data-jpa") {
		exclude group: 'org.springframework.boot', module: 'spring-boot-starter-logging'
	}

	// Data Validation
	implementation("org.springframework.boot:spring-boot-starter-validation") {
		exclude group: 'org.springframework.boot', module: 'spring-boot-starter-logging'
	}

	// Web MVC
	implementation("org.springframework.boot:spring-boot-starter-web") {
		exclude group: 'org.springframework.boot', module: 'spring-boot-starter-logging'
	}

	// ASLI Lib
	implementation("com.asliri.core:spring-sdk:0.0.0.11") {
		exclude group: 'org.springframework.boot', module: 'spring-boot-starter-logging'
	}

	// Logging
	implementation 'org.springframework.boot:spring-boot-starter-log4j2'

	// JavaFX
	implementation 'org.openjfx:javafx-controls:23.0.1'
	implementation 'org.openjfx:javafx-fxml:23.0.1'

	// JNA
	implementation 'net.java.dev.jna:jna:5.16.0'

	// MaterialFX
	implementation 'io.github.palexdev:materialfx:11.17.0'

	// SpringBoot JavaFX
	implementation 'net.rgielen:javafx-weaver-spring-boot-starter:1.3.0'

	// DevTools
	developmentOnly 'org.springframework.boot:spring-boot-devtools'

	// Lombok
	compileOnly 'org.projectlombok:lombok'
	annotationProcessor 'org.projectlombok:lombok'

	// H2 Database
	runtimeOnly 'com.h2database:h2'

	// Testing
	testImplementation 'org.springframework.boot:spring-boot-starter-test'
	testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}

tasks.named('test') {
	useJUnitPlatform()
}

task copyDylib(type: Copy) {
	from 'native'
	include '*.dylib'
	into "$buildDir/libs"
}

build.dependsOn(copyDylib)